// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TQv-xavtISxEY4MVZCQHvoWVgEhxAjg',
    appId: '1:1022786242261:web:0382102be454c4ed87845c',
    messagingSenderId: '1022786242261',
    projectId: 'trendera-2fdc0',
    authDomain: 'trendera-2fdc0.firebaseapp.com',
    storageBucket: 'trendera-2fdc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgn9m7DVE-dY0Q5OsjXMH5Wfj5pYNSnY',
    appId: '1:1022786242261:android:df71890ba2a1702587845c',
    messagingSenderId: '1022786242261',
    projectId: 'trendera-2fdc0',
    storageBucket: 'trendera-2fdc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDszlof6Qcmk_4ay-65zoiKqRfgQxtOCu0',
    appId: '1:1022786242261:ios:382627b0a8f01a3287845c',
    messagingSenderId: '1022786242261',
    projectId: 'trendera-2fdc0',
    storageBucket: 'trendera-2fdc0.firebasestorage.app',
    iosBundleId: 'com.example.trendera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDszlof6Qcmk_4ay-65zoiKqRfgQxtOCu0',
    appId: '1:1022786242261:ios:382627b0a8f01a3287845c',
    messagingSenderId: '1022786242261',
    projectId: 'trendera-2fdc0',
    storageBucket: 'trendera-2fdc0.firebasestorage.app',
    iosBundleId: 'com.example.trendera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_TQv-xavtISxEY4MVZCQHvoWVgEhxAjg',
    appId: '1:1022786242261:web:1481b1ab65e627dc87845c',
    messagingSenderId: '1022786242261',
    projectId: 'trendera-2fdc0',
    authDomain: 'trendera-2fdc0.firebaseapp.com',
    storageBucket: 'trendera-2fdc0.firebasestorage.app',
  );
}
